# Generated by Django 5.2.5 on 2025-08-20 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BACnetDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField(help_text='BACnet device instance number', unique=True)),
                ('address', models.CharField(help_text='IP address of device', max_length=50)),
                ('vendor_id', models.IntegerField(help_text='BACnet vendor ID')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now_add=True)),
                ('is_online', models.BooleanField(default=True)),
                ('points_read', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'BACnet Device',
                'verbose_name_plural': 'BACnet Devices',
                'ordering': ['device_id'],
            },
        ),
        migrations.CreateModel(
            name='BACnetPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(help_text='BACnet object type', max_length=50)),
                ('instance_number', models.CharField(help_text='BACnet instance number', max_length=50)),
                ('identifier', models.CharField(help_text='Full identifier', max_length=50)),
                ('object_name', models.CharField(blank=True, help_text='Human-readable name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Point description')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(help_text='Device this point belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='points', to='discovery.bacnetdevice')),
            ],
            options={
                'verbose_name': 'BACnet Point',
                'verbose_name_plural': 'BACnet Points',
                'ordering': ['object_type', 'instance_number'],
                'unique_together': {('device', 'object_type', 'instance_number')},
            },
        ),
    ]
