# Generated by Django 5.2.5 on 2025-08-26 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bacnetpoint",
            name="data_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("real", "Real (Float)"),
                    ("unsigned", "Unsigned Integer"),
                    ("integer", "Signed Integer"),
                    ("boolean", "Boolean"),
                    ("enumerated", "Enumerated"),
                    ("string", "Character String"),
                    ("bitstring", "Bit String"),
                    ("date", "Date"),
                    ("time", "Time"),
                    ("datetime", "Date Time"),
                    ("null", "Null"),
                ],
                help_text="BACnet data type",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bacnetpoint",
            name="present_value",
            field=models.CharField(
                blank=True, help_text="Current sensor reading", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="bacnetpoint",
            name="units",
            field=models.CharField(
                blank=True, help_text="Engineering units (°F, PSI, etc.)", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="bacnetpoint",
            name="value_last_read",
            field=models.DateTimeField(
                blank=True, help_text="When value was last read", null=True
            ),
        ),
        migrations.AlterField(
            model_name="bacnetpoint",
            name="identifier",
            field=models.CharField(help_text="Full identifier", max_length=100),
        ),
        migrations.AlterField(
            model_name="bacnetpoint",
            name="instance_number",
            field=models.IntegerField(help_text="BACnet instance number"),
        ),
        migrations.CreateModel(
            name="BACnetReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(help_text="Sensor reading value", max_length=100),
                ),
                (
                    "units",
                    models.CharField(
                        blank=True, help_text="Engineering units", max_length=50
                    ),
                ),
                (
                    "read_time",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When reading was taken"
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        blank=True,
                        help_text="Reading quality (good, bad, uncertain)",
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        blank=True, help_text="Reading priority", null=True
                    ),
                ),
                (
                    "point",
                    models.ForeignKey(
                        help_text="Point this reading belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="discovery.bacnetpoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "BACnet Reading",
                "verbose_name_plural": "BACnet Readings",
                "ordering": ["-read_time"],
                "indexes": [
                    models.Index(
                        fields=["point", "-read_time"],
                        name="discovery_b_point_i_cf9262_idx",
                    )
                ],
            },
        ),
    ]
