# Generated by Django 5.2.5 on 2025-09-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0002_bacnetpoint_data_type_bacnetpoint_present_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bacnetdevice",
            name="points_read",
            field=models.BooleanField(default=False),
        ),
    ]
