# Generated by Django 5.2.6 on 2025-09-10 05:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0004_bacnetreading_anomaly_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bacnetreading",
            name="read_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, help_text="When reading was taken"
            ),
        ),
    ]
