# Generated by Django 5.2.6 on 2025-09-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0005_alter_bacnetreading_read_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="bacnetdevice",
            name="deactivated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bacnetdevice",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
