# Generated by Django 5.2.6 on 2025-10-01 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0006_bacnetdevice_deactivated_at_bacnetdevice_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildingEnergyForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("forecast_date", models.DateField()),
                ("forecast_hour", models.IntegerField()),
                ("predicted_temperature", models.FloatField()),
                ("predicted_hvac_load", models.FloatField()),
                ("predicted_cost", models.FloatField(blank=True, null=True)),
                ("confidence_score", models.FloatField()),
                ("model_version", models.CharField(default="v1.0", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("forecast_date", "forecast_hour")},
            },
        ),
        migrations.CreateModel(
            name="EnergyMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(help_text="Date for which metrics are calculated"),
                ),
                ("avg_temperature", models.FloatField()),
                ("min_temperature", models.FloatField()),
                ("max_temperature", models.FloatField()),
                ("temperature_variance", models.FloatField()),
                ("estimated_hvac_load", models.FloatField(help_text="kWh estimated")),
                ("peak_demand_hour", models.IntegerField(blank=True, null=True)),
                ("efficiency_score", models.FloatField(blank=True, null=True)),
                ("predicted_next_day_load", models.FloatField(blank=True, null=True)),
                ("confidence_interval", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="discovery.bacnetdevice",
                    ),
                ),
            ],
            options={
                "unique_together": {("date", "device")},
            },
        ),
    ]
