# Generated by Django 5.2.6 on 2025-10-01 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0007_buildingenergyforecast_energymetrics"),
    ]

    operations = [
        migrations.RenameField(
            model_name="energymetrics",
            old_name="confidence_interval",
            new_name="confidence_score",
        ),
    ]
