# Generated by Django 5.2.6 on 2025-10-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0008_rename_confidence_interval_energymetrics_confidence_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="VirtualBACnetDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.IntegerField(
                        help_text="BACnet device instance number (must be unique)",
                        unique=True,
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        help_text="Human-readable device name", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of this virtual device",
                    ),
                ),
                (
                    "port",
                    models.IntegerField(
                        default=47808, help_text="BACnet UDP port (default 47808)"
                    ),
                ),
                (
                    "is_running",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the virtual device is currently running",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Virtual BACnet Device",
                "verbose_name_plural": "Virtual BACnet Devices",
                "ordering": ["device_id"],
            },
        ),
        migrations.RemoveField(
            model_name="alarmhistory",
            name="device",
        ),
        migrations.RemoveField(
            model_name="alarmhistory",
            name="point",
        ),
        migrations.DeleteModel(
            name="BuildingEnergyForecast",
        ),
        migrations.AlterUniqueTogether(
            name="energymetrics",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="energymetrics",
            name="device",
        ),
        migrations.RemoveField(
            model_name="maintenancelog",
            name="device",
        ),
        migrations.AlterUniqueTogether(
            name="sensorreadingstats",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="sensorreadingstats",
            name="point",
        ),
        migrations.RemoveField(
            model_name="bacnetreading",
            name="anomaly_score",
        ),
        migrations.RemoveField(
            model_name="bacnetreading",
            name="data_quality_score",
        ),
        migrations.RemoveField(
            model_name="bacnetreading",
            name="is_anomaly",
        ),
        migrations.DeleteModel(
            name="AlarmHistory",
        ),
        migrations.DeleteModel(
            name="EnergyMetrics",
        ),
        migrations.DeleteModel(
            name="MaintenanceLog",
        ),
        migrations.DeleteModel(
            name="SensorReadingStats",
        ),
    ]
